- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "priority: high"
  color: "ff0000"
  description: "High priority issue"

- name: "priority: medium"
  color: "ffa500"
  description: "Medium priority issue"

- name: "priority: low"
  color: "00ff00"
  description: "Low priority issue"

- name: "type: feature"
  color: "0e8a16"
  description: "New feature"

- name: "type: bug"
  color: "d73a4a"
  description: "Bug fix"

- name: "type: refactor"
  color: "6f42c1"
  description: "Code refactoring"

- name: "type: test"
  color: "f9d0c4"
  description: "Test related"

- name: "type: chore"
  color: "c5def5"
  description: "Maintenance task"
