name: Q&A
description: Ask a question and get help from the community
title: "[Q&A] "
labels: ["question", "help-wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Ask a question and get help from the community!

  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: Please describe your question clearly
      placeholder: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. Windows 10, macOS 12.0, Ubuntu 20.04]
        - VS Code Version: [e.g. 1.74.0]
        - Bubulle Extension Version: [e.g. 0.0.1]
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce (if applicable)
      description: If this is about a bug or issue, please describe the steps
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: Describe what actually happened

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any additional context, screenshots, or logs
      placeholder: Add any other context about the question here
